---
server:
  port: 8444

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,mappings
    health:
      enabled: true
    prometheus:
      enabled: true
    mappings:
      enabled: true
